services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5732:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 12

  api:
    build:
      context: ./backend
    restart: unless-stopped
    environment:
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      RESET_KEY: ${RESET_KEY}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8381:8081"
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8081/api/health', timeout=2)",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  web:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    restart: unless-stopped
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "8380:8080"

volumes:
  db_data:
